substitutions:
  name: sdm120
  device_description: "Esphome component for SDM modbus"
  friendly_name: SDM

esphome:
  name: ${name}
#  friendly_name: ${friendly_name}
  comment: Eastron SDM 120 2x


## MH-ET-LIVE  ESP32: / on V1
esp32:
  board: mhetesp32minikit
  framework:
    type: arduino

# Enable logging
logger:
  logs:
    modbus_controller.sensor: WARN
    modbus_controller.output: WARN
    modbus.number: WARN
    esp32.preferences: WARN
    sensor: WARN
    text_sensor: WARN
    number: WARN 

# Enable Home Assistant API
api:
  reboot_timeout: 0s

#update for esphome 2024.6.0
# OTA:
ota:
  platform: esphome
#  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}"
    password: "configesp"
    
captive_portal:
    
web_server:
  port: 80

### modbus ### on V1
uart:
  id: mod_bus
  tx_pin: GPIO23
  rx_pin: GPIO19
  baud_rate: 9600
  stop_bits: 1
  parity: NONE

modbus:
  id: modbus1
  send_wait_time: 200ms

#### 2x EASTRON SDM120 Single phase kWh meter
modbus_controller:
  - id: SDM1
    ## SDM120 meter slaveadress 2 ???
    address: 2
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    ## change parity to none on the SDM120 meter. Baudrate to 9600
  - id: SDM2
    ## SDM120 meter slaveadress 3 ???
    address: 3
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    ## change parity to none on the SDM120 meter. Baudrate to 9600

sensor:
    ## Power1
  - platform: modbus_controller
    modbus_controller_id: SDM1
    name: SDM1 Power
    register_type: read
    address: 12
    value_type: FP32
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    accuracy_decimals: 0
    filters:
      - multiply: 1

    ## Voltage1
  - platform: modbus_controller
    modbus_controller_id: SDM1
    name: SDM1 Voltage
    register_type: read
    address: 0
    value_type: FP32
    unit_of_measurement: V
    state_class: measurement
    device_class: voltage
    accuracy_decimals: 0
    filters:
      - multiply: 1

    ## Current1
  - platform: modbus_controller
    modbus_controller_id: SDM1
    name: SDM1 Current
    register_type: read
    address: 6
    value_type: FP32
    unit_of_measurement: A
    state_class: measurement
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 1

    ## Energy1
  - platform: modbus_controller
    modbus_controller_id: SDM1
    name: SDM1 Total Energy
    register_type: read
    address: 342
    value_type: FP32
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

    ## Power2
  - platform: modbus_controller
    modbus_controller_id: SDM2
    name: SDM2 Power
    register_type: read
    address: 12
    value_type: FP32
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    accuracy_decimals: 0
    filters:
      - multiply: 1

    ## Voltage2
  - platform: modbus_controller
    modbus_controller_id: SDM2
    name: SDM2 Voltage
    register_type: read
    address: 0
    value_type: FP32
    unit_of_measurement: V
    state_class: measurement
    device_class: voltage
    accuracy_decimals: 0
    filters:
      - multiply: 1

    ## Current2
  - platform: modbus_controller
    modbus_controller_id: SDM2
    name: SDM2 Current
    register_type: read
    address: 6
    value_type: FP32
    unit_of_measurement: A
    state_class: measurement
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 1

    ## Energy2
  - platform: modbus_controller
    modbus_controller_id: SDM2
    name: SDM2 Total Energy
    register_type: read
    address: 342
    value_type: FP32
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    
