substitutions:
  procon_version: MelcoBEMS MINI firmware versie
  heat_pump_frequency_master: Warmtepomp frequentie – Master  
  temperature_setpoint_zone_1: Ingestelde temperatuur
  flow_temperature_setpoint_zone_1: Ingestelde flow temperatuur
  legionella_temperature_setpoint: Ingestelde Legionella temperatuur
  DHW_temperature_drop: SWW temperatuur hysterese
  room_temperature_zone_1: Kamer temperatuur
  refrigerant_liquid_temperature: Koelmiddelvloeistof temperatuur
  outdoor_ambient_temperature: Buiten temperatuur
  flow_temperature: Flow temperatuur
  return_temperature: Retour temperatuur
  tank_water_temperature: SWW boiler temperatuur
  return_temperature_setpoint_zone_1: Ingestelde retour temperature
  boiler_flow_temperature: Boiler flow temperatuur
  boiler_return_temperature: Boiler retour temperatuur
  heat_pump_run_time: Warmtepomp runtime
  energy_used_heating: Energie gebruikt verwarmen
  energy_used_cooling: Energie gebruikt koelen
  energy_used_dhw: Energie gebruikt SWW
  last_measured_total_energy_consumption: Laatst gemeten totale energie verbruikt
  energy_produced_heating: Energy geproduceerd verwarmen
  energy_produced_cooling: Energy geproduceerd koelen
  energy_produced_dhw: Energy geproduceerd SWW
  cop_heating: COP verwarmen
  cop_cooling: COP koelen
  cop_dhw: COP SWW
  last_measured_total_energy_produced: Laatst gemeten totale energie geproduceerd
  flow_rate: Flow
  consumed_electric_power: Verbruikt elektrisch vermogen
  produced_power: Geproduceerd thermisch vermogen
  esp_home_version: Esphome Versie
  fault_code: Fout code
  system_type_detected: Systeem type gedetecteerd
  defrost: Ontdooien
  residual_heat_removal: Residual heat removal
  refrigerant_error_info: Koelmiddel fout info
  seven_segment_display_error_code_digit_1: 7-Segment display fout code digit 1
  seven_segment_display_error_code_digit_2: 7-Segment display fout code digit 2
  heat_source_status: Status verwarmingsbron
  model_profile_1: Model Profiel 1
  operating_mode: Werkings mode
  set_tank_water_temperature: Ingestelde boiler doel temperatuur
  hc_thermostat_target_temperature_zone_1: Verw/Koelen doel temperatuur
  thermostat_target_temperature_zone_1: Thermostaat doel temperatuur
  relay: Relais
  operating_mode_dhw: DHW eco modus
  force_dhw: Forceer SWW
  set_holiday: Vakantie modus
  cooling_on_prohibit_zone_1: Koelen verboden
  system_on_off: Systeem aan/uit
  ac_mode_zone_1: A/C mode
  hc_control_type: HC controle type

  auto: Auto
  initialize: Initialiseren
  unknown: Onbekend
  hours: uur
  days: dagen
