substitutions:
  name: panasonic
  comment: Panasonic warmtepomp

esphome:
  name: ${name}
  comment: ${comment}

## lilygo T7-S3  ESP32S3:
esp32:
  board: adafruit_feather_esp32s3_nopsram
  framework:
    type: arduino

# Enable logging
logger:
  logs:
    modbus_controller.sensor: WARN
    modbus_controller.output: WARN
    modbus.number: WARN
    esp32.preferences: WARN
    sensor: WARN
    text_sensor: WARN
    number: WARN 

# Enable Home Assistant API
api:
  reboot_timeout: 0s

# Enable Over The Air updates  
ota:
#  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}"
    password: "configesp"
    
captive_portal:
    
web_server:
  port: 80

# Modbus uart
uart:
  id: mod_bus
  baud_rate: 9600
  stop_bits: 1
  tx_pin: 16
  rx_pin: 12

modbus:
  id: modbus1
  send_wait_time: 200ms

#### 2x EASTRON SDM120 Single phase kWh meter
modbus_controller:
  - id: SDM1
    ## SDM120 meter slaveadress 2
    address: 2
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    ## change parity to none on the SDM120 meter. Baudrate to 9600
  - id: SDM2
    ## SDM120 meter slaveadress 3
    address: 3
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 10s
    ## change parity to none on the SDM120 meter. Baudrate to 9600

## Option for 2x I2C connectors
## Comment with # if not used.
i2c:  
  - id: bus_a
    sda: 13
    scl: 14
    scan: true

  - id: bus_b
    sda: 10
    scl: 18
    scan: true

## Option for multiple DS18b20 on last 3 terminals -/Signal/+ ON PCB: Resistor 4k7 needed for R2
## Comment with # if not used.
### DS18b20's ###
#dallas:
#  - pin: 8
#    update_interval: 30s

# Enable Status LED.
status_led:
  pin:
    number: 17

button:
  - platform: restart
    id: restart_button
    name: ${name} Herstart ESP module

switch:
  ## Relay
  - platform: gpio
    pin:
      number: 5
      inverted: false
    name: ${name} Power
    id: wp_relay
    icon: mdi:alarm-bell

sensor:
  # M5stack KMeterIso - https://docs.m5stack.com/en/unit/KMeterISO%20Unit
  - platform: kmeteriso
    temperature:
      name: ${name} Aanvoer temperatuur
    internal_temperature:
      name: ${name} Internal temperature
      entity_category: diagnostic
    update_interval: 5s
    i2c_id: bus_a

  - platform: kmeteriso
    temperature:
      name: ${name} Retour temperatuur
    internal_temperature:
      name: ${name} Internal temperature2
      entity_category: diagnostic
    update_interval: 5s
    i2c_id: bus_b

    # SDM120 meter1
    ## Power1
  - platform: modbus_controller
    modbus_controller_id: SDM1
    name: ${name} SDM1 Power
    register_type: read
    address: 12
    value_type: FP32
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    accuracy_decimals: 0
    filters:
      - multiply: 1

    ## Voltage1
  - platform: modbus_controller
    modbus_controller_id: SDM1
    name: ${name} SDM1 Voltage
    register_type: read
    address: 0
    value_type: FP32
    unit_of_measurement: V
    state_class: measurement
    device_class: voltage
    accuracy_decimals: 0
    filters:
      - multiply: 1

    ## Current1
  - platform: modbus_controller
    modbus_controller_id: SDM1
    name: ${name} SDM1 Current
    register_type: read
    address: 6
    value_type: FP32
    unit_of_measurement: A
    state_class: measurement
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 1

    ## Energy1
  - platform: modbus_controller
    modbus_controller_id: SDM1
    name: ${name} SDM1 Total Energy
    register_type: read
    address: 342
    value_type: FP32
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

    # SDM120 meter2
    ## Power2
  - platform: modbus_controller
    modbus_controller_id: SDM2
    name: ${name} SDM2 Power
    register_type: read
    address: 12
    value_type: FP32
    unit_of_measurement: W
    state_class: measurement
    device_class: power
    accuracy_decimals: 0
    filters:
      - multiply: 1

    ## Voltage2
  - platform: modbus_controller
    modbus_controller_id: SDM2
    name: ${name} SDM2 Voltage
    register_type: read
    address: 0
    value_type: FP32
    unit_of_measurement: V
    state_class: measurement
    device_class: voltage
    accuracy_decimals: 0
    filters:
      - multiply: 1

    ## Current2
  - platform: modbus_controller
    modbus_controller_id: SDM2
    name: ${name} SDM2 Current
    register_type: read
    address: 6
    value_type: FP32
    unit_of_measurement: A
    state_class: measurement
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 1

    ## Energy2
  - platform: modbus_controller
    modbus_controller_id: SDM2
    name: ${name} SDM2 Total Energy
    register_type: read
    address: 342
    value_type: FP32
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

## Option for multiple DS18b20 on last 3 terminals -/Signal/+ 
## Comment with # if not used.
## 2x ds18b20: 
#  - platform: dallas
#    address: 0x923c01d075935628  ##find adress in esphome log
#    name: ${name} Temperature 1
#    id: temperature_1
#    filters:
#    - filter_out: NAN

#  - platform: dallas
#    address: 0x1f3c01d07519cb28  ##find adress in esphome log
#    name: ${name} Temperature 2
#    id: temperature_2
#    filters:
#    - filter_out: NAN

## Option for DHT11 or DHT22 on last 3 terminals -/Signal/+ 
## Comment with # if not used.
#  - platform: dht
#    model: DHT11
#    pin: 8
#    temperature:
#      name: ${name} Temperature
#      id: panasonic_temperature
#    humidity:
#      name: ${name} Humidity
#      id: panasonic_humidity
#    update_interval: 15s