substitutions:
  name: lg
  device_description: "Esphome component for LG Heatpump"
  friendly_name: LG

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: LG warmtepomp
  ## Get rid of CDC error:
  platformio_options:
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"

## lilygo T7-S3  ESP32S3:
esp32:
  board: adafruit_feather_esp32s3_nopsram
  framework:
    type: arduino

# Enable logging
logger:
  logs:
    modbus_controller.sensor: WARN
    modbus_controller.output: WARN
    modbus.number: WARN
    esp32.preferences: WARN
    sensor: WARN
    text_sensor: WARN
    number: WARN 

# Enable Home Assistant API
api:
  reboot_timeout: 0s

# Enable Over The Air updates  
ota:
#  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: "configesp"
    
captive_portal:
    
web_server:
  port: 80

## Option for 2x I2C connectors
## Comment with # if not used.
#i2c:  
#  - id: bus_a
#    sda: 13
#    scl: 14
#    scan: true

#  - id: bus_b
#    sda: 10
#    scl: 18
#    scan: true

## Option for multiple DS18b20 on last 3 terminals -/Signal/+ ON PCB: Resistor 4k7 needed for R2
## Comment with # if not used.
### DS18b20's ###
#dallas:
#  - pin: 8
#    update_interval: 30s

### modbus ###
uart:
  id: mod_bus
  tx_pin: 16
  rx_pin: 12 
  baud_rate: 9600
  stop_bits: 1
  
modbus:
  id: modbus1
  send_wait_time: 200ms

modbus_controller:
  - id: ${name}
    address: 1 # the Modbus device addr
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 15s

# Enable Status LED.
status_led:
  pin:
    number: 17

sensor:
## Option for multiple DS18b20 on last 3 terminals -/Signal/+ ON PCB: Resistor 4k7 needed for R2
## Comment with # if not used.
## 2x ds18b20: 
#  - platform: dallas
#    address: 0x923c01d075935628  ##find adress in esphome log
#    name: "Temperature 1"
#    id: temperature_1
#    filters:
#    - filter_out: NAN

#  - platform: dallas
#    address: 0x1f3c01d07519cb28  ##find adress in esphome log
#    name: "Temperature 2"
#    id: temperature_2
#    filters:
#    - filter_out: NAN

## Option for DHT11 or DHT22 on last 3 terminals -/Signal/+ ON PCB: Resistor 10K needed for R2
## Comment with # if not used.
#  - platform: dht
#    model: DHT11
#    pin: 8
#    temperature:
#      name: Temperature
#      id: mitsubishi_temperature
#    humidity:
#      name: Humidity
#      id: mitsubishi_humidity
#    update_interval: 15s

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Bedrijfsmodus"
    id: bedrijfsmodus
    register_type: read
    address: 1
    #skip_updates: 12
    value_type: U_WORD
    icon: mdi:information-outline

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Water retour"
    id: water_temp_retour
    register_type: read
    address: 2
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:thermometer-chevron-down

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Water aanvoer"
    id: water_temp_aanvoer
    register_type: read
    address: 3
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:thermometer-chevron-up

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "SWW Temperatuur"
    id: sww_temp
    register_type: read
    address: 5
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:thermometer-water

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "RMC temperatuur"
    id: binnen_temp
    register_type: read
    address: 7
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:home-thermometer

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Flow Rate"
    id: current_flow_rate
    register_type: read
    address: 8
    unit_of_measurement: "l/min"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    lambda: |-
     if (id(pump_running).state) return x;
      else return 0.0;
    icon: mdi:waves-arrow-right

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Buitentemperatuur"
    id: buiten_temp
    register_type: read
    address: 12
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    icon: mdi:weather-cloudy
    filters:
      - multiply: 0.1
      - sliding_window_moving_average:
          window_size: 60
          send_every: 30
    on_value:
      then:
        - lambda: !lambda |-
            static float prev_oat = -100.0;
            if (abs(round(x) - round(prev_oat)) > 0.1) {
              fsm.update_stooklijn();
              prev_oat = x;
            }

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Pipe in Temp"
    id: temp16
    register_type: read
    address: 16
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Pipe Out Temp"
    id: temp17
    register_type: read
    address: 17
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Suction Temp"
    id: temp18
    register_type: read
    address: 18
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Fan RPM"
    id: temp19
    register_type: read
    address: 19
    unit_of_measurement: "rpm"
    value_type: S_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Condenser Temp"
    id: condensor_temp
    register_type: read
    address: 20
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    icon: mdi:hvac

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "High Press"
    id: high_press
    register_type: read
    address: 22
    value_type: U_WORD
    accuracy_decimals: 0
    unit_of_measurement: "mbar"
    icon: mdi:meter-electric-outline

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Low Press"
    id: low_press
    register_type: read
    address: 23
    value_type: U_WORD
    accuracy_decimals: 0
    unit_of_measurement: "mbar"

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Compressor Hz"
    id: compressor_rpm
    register_type: read
    address: 24
    unit_of_measurement: "Hz"
    value_type: U_WORD
    accuracy_decimals: 0
    icon: mdi:car-turbocharger

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Doeltemperatuur"
    id: doel_temp
    register_type: holding
    address: 2
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    skip_updates: 3
    filters:
      - multiply: 0.1
    icon: mdi:home-thermometer-outline

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "SWW Doeltemperatuur"
    id: sww_target
    register_type: holding
    address: 8
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    skip_updates: 3
    filters:
      - multiply: 0.1
    icon: mdi:thermometer-water

text_sensor:

  # Expose ESPHome version as sensor.
  - platform: version
    name: Esphome Version
    hide_timestamp: true

number:

  - platform: modbus_controller
    modbus_controller_id: ${name}
    id: water_temp_target_output
    register_type: holding
    address: 2
    value_type: U_WORD
    step: 0.1
    multiply: 10

switch:

## Option for Relay
## Comment with # if not used.
  ## Relay
  - platform: gpio
    pin:
      number: 5
      inverted: false
    name: Relay
    id: relay
    icon: mdi:alarm-bell

  - platform: modbus_controller
    name: "Silent Mode"
    modbus_controller_id: ${name}
    id: silent_mode_switch
    register_type: coil
    address: 2
    icon: mdi:volume-off

  - platform: modbus_controller
    name: "SWW On/Off"
    modbus_controller_id: ${name}
    id: sww_on_off
    register_type: coil
    address: 1
    icon: mdi:shower-head

binary_sensor:

  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Pump Running"
    id: pump_running
    register_type: discrete_input
    skip_updates: 1
    address: 1
    icon: mdi:pump
  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Compressor Running"
    id: compressor_running
    register_type: discrete_input
    skip_updates: 1
    address: 3
    icon: mdi:car-turbocharger
  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Defrosting"
    id: defrosting
    register_type: discrete_input
    skip_updates: 1
    address: 4
    icon: mdi:snowflake-melt
  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "SWW Heating"
    id: sww_heating
    register_type: discrete_input
    skip_updates: 1
    address: 5
    icon: mdi:shower-head
  - platform: modbus_controller
    modbus_controller_id: ${name}
    name: "Silent Mode"
    id: silent_mode_state
    register_type: discrete_input
    skip_updates: 1
    address: 7
    icon: mdi:volume-off

select:

    ## A/C mode – Zone 1 (FC6: 28, 40029)
  - platform: modbus_controller
    modbus_controller_id: ${name}
    id: ac_mode_zone_1
    name: A/C mode - Zone 1
    address: 28
    optionsmap:
      "Heating room": 0
      "Heating flow": 1
      "Heating curve": 2
      "Cooling room": 3
      "Cooling flow": 4
      "Floor Dryup": 5
    entity_category: config

    ## A/C mode – Zone 2 (FC6: 29, 40030)
  - platform: modbus_controller
    modbus_controller_id: ${name}
    id: ac_mode_zone_2
    name: A/C mode - Zone 2
    address: 29
    optionsmap:
      "Heating room": 0
      "Heating flow": 1
      "Heating curve": 2
      "Cooling room": 3
      "Cooling flow": 4
      "Floor Dryup": 5
    entity_category: config

    ## HC Control Type (FC6: 58, 40059)
  - platform: modbus_controller
    modbus_controller_id: ${name}
    id: hc_control_type
    name: HC Control Type
    address: 58
    optionsmap:
      "Heating": 0
      "Cooling": 1
    entity_category: config