substitutions:
  name: elga
  device_description: "Esphome component for Remeha Elga Ace with GTW-08 modbus pcb extension"
  ## Order GTW-08 PCB @ https://pumpen-heizung.de/Remeha-7721982-Schnittstelle-Modbus-RTU-Gateway-GTW-08
  ## Dutch manual: https://tools.remeha.nl/wp-content/uploads/sites/3/2020/08/Lijst-van-parameters-voor-GTW08.pdf
  friendly_name: Elga

esphome:
  name: ${name}
#  friendly_name: ${friendly_name}
  comment: Remeha Elga Ace warmtepomp
  ## Get rid of CDC error ON V2
#  platformio_options:
#    board_build.extra_flags:
#      - "-DARDUINO_USB_CDC_ON_BOOT=0"

## MH-ET-LIVE  ESP32: / on V1
esp32:
  board: mhetesp32minikit
  framework:
    type: arduino

## lilygo T7-S3  ESP32S3 / on V2
#  board: adafruit_feather_esp32s3_nopsram
#  framework:
#    type: arduino

# Enable logging
logger:
  logs:
    modbus_controller.sensor: WARN
    modbus_controller.output: WARN
    modbus.number: WARN
    esp32.preferences: WARN
    sensor: WARN
    text_sensor: WARN
    number: WARN 

# Enable Home Assistant API
api:
  reboot_timeout: 0s

# Enable Over The Air updates  
ota:
#  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: "configesp"
    
captive_portal:
    
web_server:
  port: 80

## Option for 2x I2C connectors on V2
## Comment with # if not used.
#i2c:  
#  - id: bus_a
#    sda: 13
#    scl: 14
#    scan: true

#  - id: bus_b
#    sda: 10
#    scl: 18
#    scan: true

## Option for multiple DS18b20 on last 3 terminals -/Signal/+ ON PCB: Resistor 4k7 needed for R2 ON V2
## Comment with # if not used.
### DS18b20's ###
#dallas:
#  - pin: 8
#    update_interval: 30s

### modbus ### on V1
uart:
  id: mod_bus
  tx_pin: 23 
  rx_pin: 19 
  baud_rate: 9600
  stop_bits: 1
  parity: none

### modbus ### on V1
#uart:
#  id: mod_bus
#  tx_pin: 16
#  rx_pin: 12 
#  baud_rate: 9600
#  stop_bits: 1
#  parity: none

modbus:
  id: modbus1
  send_wait_time: 200ms

modbus_controller:
  - id: ${name}
    address: 100 # the Modbus device addr set by switch (see manual)
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 15s

# Enable Status LED.
status_led:
  pin:
    number: 17

sensor:
## Option for multiple DS18b20 on last 3 terminals -/Signal/+ ON PCB: Resistor 4k7 needed for R2 on V2
## Comment with # if not used.
## 2x ds18b20: 
#  - platform: dallas
#    address: 0x923c01d075935628  ##find adress in esphome log
#    name: "Temperature 1"
#    id: temperature_1
#    filters:
#    - filter_out: NAN

#  - platform: dallas
#    address: 0x1f3c01d07519cb28  ##find adress in esphome log
#    name: "Temperature 2"
#    id: temperature_2
#    filters:
#    - filter_out: NAN

## Option for DHT11 or DHT22 on last 3 terminals -/Signal/+ ON PCB: Resistor 10K needed for R2 on V2
## Comment with # if not used.
#  - platform: dht
#    model: DHT11
#    pin: 8
#    temperature:
#      name: Temperature
#      id: mitsubishi_temperature
#    humidity:
#      name: Humidity
#      id: mitsubishi_humidity
#    update_interval: 15s

  - id: elga_aanvoertemperatuur_combi
    name: Elga Aanvoertemperatuur Combi #FlowTemperatureReceived
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding  # of read ?
    address: 273
    bitmask: 1
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer-chevron-down
    filters:
      - multiply: 0.01

  - id: elga_retourtemperatuur
    name: Elga Retourtemperatuur #ReturnTemperatureReceived #FlowTemperatureReceived
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding # of read ?
    address: 274
    bitmask: 1
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer-chevron-down
    filters:
      - multiply: 0.01

  - id: elga_waterdruk
    name: Elga Waterdruk #ApWaterPressure #FlowTemperatureReceived
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding # of read ?
    address: 409
    bitmask: 1
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer-chevron-down
    filters:
      - multiply: 0.1

  - id: elga_buitentemperatuur
    name: Elga Buitentemperatuur ##varApTOutside
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding # of read ?
    address: 884
    bitmask: 1
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer-chevron-down
    filters:
      - multiply: 0.01

  - id: elga_aanvoertemperatuur_wp
    name: Elga Aanvoertemperatuur WP #remeha_varHpHeatPumpTF
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding # of read ?
    address: 403
    bitmask: 1
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer-chevron-down
    filters:
      - multiply: 0.01

  - id: elga_waterdoorstroming
    name: Elga Waterdoorstroming #varApFlowmeter
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding # of read ?
    address: 410
    bitmask: 1
    value_type: U_WORD
    unit_of_measurement: "l/min"
    accuracy_decimals: 1
    icon: mdi:thermometer-chevron-down
    filters:
      - multiply: 0.01

  - id: elga_aanvoertemperatuur_setpoint
    name: Elga Aanvoertemperatuur setpoint" #varZoneTemperatureSetpoint
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding # of read ?
    address: 1101
    bitmask: 1
    value_type: U_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer-chevron-down
    filters:
      - multiply: 0.01

  - id: elga_ruimtetemperatuur_setpoint
    name: Elga Ruimtesetpoint #remeha_varZoneTRoomSetpoint
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding # of read ?
    address: 1102
    bitmask: 1
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer-chevron-down
    filters:
      - multiply: 0.1

  - id: elga_ruimtetemperatuur
    name: Elga Ruimtetemperatuur #varZoneTRoom
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding # of read ?
    address: 1104
    bitmask: 1
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: mdi:thermometer-chevron-down
    filters:
      - multiply: 0.1

  - id: elga_energieverbruik_totaal
    name: Elga Energieverbruik totaal #varApChEnergyConsumption
    platform: modbus_controller
    modbus_controller_id: ${name}
    register_type: holding # of read ?
    address: 433
    bitmask: 1
    value_type: U_DWORD
    unit_of_measurement: "kWh"
    state_class: total_increasing
    accuracy_decimals: 1
    icon: mdi:thermometer-chevron-down
    filters:
      - multiply: 0.01
